int do_signal32(void) {return 0;}
int sys32_sigaction(void) {return 0;}
int sys32_sigsuspend(void) {return 0;}
int sys32_sigpending(void) {return 0;}
int sys32_sigreturn(void) {return 0;}
int sys32_rt_sigreturn(void) {return 0;}
int sys32_rt_sigaction(void) {return 0;}
int sys32_rt_sigprocmask(void) {return 0;}
int sys32_rt_sigpending(void) {return 0;}
int sys32_rt_sigtimedwait(void) {return 0;}
int sys32_rt_sigqueueinfo(void) {return 0;}
int sys32_rt_sigsuspend(void) {return 0;}
int sys32_sigaltstack(void) {return 0;}
