/*
* Miscellaneous data structures:
* WARNING - this file is automatically generated!
*/

unsigned long orion_initrd_start[] = {
	0x1F8B0800,0x7109D539,0x02030300,0x00000000, /* 0 */
	0x00000000,0 };
unsigned long orion_initrd_size = 0x14;
