#
# Common code for all Loongson based systems
#

obj-$(CONFIG_MACH_LOONGSON) += common/

#
# Lemote Fuloong mini-PC (Loongson 2E-based)
#

obj-$(CONFIG_LEMOTE_FULOONG2E)  += fuloong-2e/

#
# Lemote Fuloong mini-PC (Loongson 2F-based)
#

obj-$(CONFIG_LEMOTE_FULOONG2F)  += fuloong-2f/
