#
# Makefile for Momentum Computer's Ocelot-C and -CS boards.
#

obj-y	 += mv-irq.o cpci-irq.o uart-irq.o int-handler.o irq.o
obj-y    += pci-irq.o pci.o prom.o reset.o setup.o 

obj-$(CONFIG_REMOTE_DEBUG) += dbg_io.o
