/* DO NOT TOUCH, AUTOGENERATED BY OFFSET.C */

#ifndef _MIPS_OFFSET_H
#define _MIPS_OFFSET_H

/* MIPS pt_regs offsets. */
#define PT_R0     64
#define PT_R1     72
#define PT_R2     80
#define PT_R3     88
#define PT_R4     96
#define PT_R5     104
#define PT_R6     112
#define PT_R7     120
#define PT_R8     128
#define PT_R9     136
#define PT_R10    144
#define PT_R11    152
#define PT_R12    160
#define PT_R13    168
#define PT_R14    176
#define PT_R15    184
#define PT_R16    192
#define PT_R17    200
#define PT_R18    208
#define PT_R19    216
#define PT_R20    224
#define PT_R21    232
#define PT_R22    240
#define PT_R23    248
#define PT_R24    256
#define PT_R25    264
#define PT_R26    272
#define PT_R27    280
#define PT_R28    288
#define PT_R29    296
#define PT_R30    304
#define PT_R31    312
#define PT_LO     320
#define PT_HI     328
#define PT_EPC    336
#define PT_BVADDR 344
#define PT_STATUS 352
#define PT_CAUSE  360
#define PT_SIZE   368

/* MIPS task_struct offsets. */
#define TASK_STATE         0
#define TASK_FLAGS         8
#define TASK_SIGPENDING    16
#define TASK_NEED_RESCHED  40
#define TASK_COUNTER       48
#define TASK_PRIORITY      56
#define TASK_MM            1400
#define TASK_STRUCT_SIZE   1480

/* MIPS specific thread_struct offsets. */
#define THREAD_REG16   1080
#define THREAD_REG17   1088
#define THREAD_REG18   1096
#define THREAD_REG19   1104
#define THREAD_REG20   1112
#define THREAD_REG21   1120
#define THREAD_REG22   1128
#define THREAD_REG23   1136
#define THREAD_REG29   1144
#define THREAD_REG30   1152
#define THREAD_REG31   1160
#define THREAD_STATUS  1168
#define THREAD_FPU     1176
#define THREAD_BVADDR  1312
#define THREAD_BUADDR  1320
#define THREAD_ECODE   1328
#define THREAD_TRAPNO  1336
#define THREAD_PGDIR   1344
#define THREAD_MFLAGS  1352
#define THREAD_CURDS   1360
#define THREAD_TRAMP   1368
#define THREAD_OLDCTX  1376

/* Linux mm_struct offsets. */
#define MM_COUNT      32
#define MM_PGD        24
#define MM_CONTEXT    88

/* Linux sigcontext offsets. */
#define SC_REGS       0
#define SC_FPREGS     256
#define SC_MDHI       512
#define SC_MDLO       520
#define SC_PC         528
#define SC_STATUS     536
#define SC_OWNEDFP    540
#define SC_FPC_CSR    544
#define SC_FPC_EIR    548
#define SC_CAUSE      552
#define SC_BADVADDR   556

#endif /* !(_MIPS_OFFSET_H) */
