# Makefile for loongson Platoform-Specific Drivers

obj-$(CONFIG_LEMOTE_YEELOONG2F_PDEV) += yeeloong_laptop.o yeeloong_battery.o

obj-$(CONFIG_LEMOTE_YEELOONG2F_PDEV_ROM) += yeeloong_pmon.o yeeloong_ec.o

obj-$(CONFIG_LEMOTE_LYNLOONG2F_PDEV) += lynloong_pc.o
